Django/makeplan/user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('^register$',views.register),
    url('^login$',views.login),
    url('^logout$',views.logout),

    url('^send_sms_regist$',views.send_sms_regist),
    url('^send_sms_login$',views.send_sms_login),
    url('^send_sms$',views.send_sms),

    # url('^bindNewMobile$',views.bind_new_mobile),
    url('^modifyUserInfo$', views.modify_userinfo),
    url('^userInfo$', views.userinfo),


    url('^uploadFile$',views.upload_file),
    url('^checkSmsCode$',views.check_sms_code),
]

Django/makeplan/user/models.py
from django.db import models

# Create your models here.
from django.db import models

class UserInfo(models.Model):
    nid = models.AutoField(primary_key=True)
    mobile = models.CharField(max_length=20, blank=False, unique=True)
    password = models.CharField(max_length=200, blank=False)
    username = models.CharField(max_length=30, blank=False, default='')
    avatar = models.CharField(max_length=200, blank=True)
    email = models.EmailField(blank=True)
    last_login = models.DateTimeField(blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username

    def to_dict(self):
        dict = {}
        dict["ident"] = self.nid
        dict["mobile"] = self.mobile
        dict["username"] = self.username
        dict["avatar"] = self.avatar
        dict["email"] = self.email
        return dict

Django/makeplan/user/views.py
# Create your views here.
import json
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from .send_sms import SendSMS
from .SMS import SendTemplateSMS
from .models import UserInfo
from . import my_tool
from django.core.cache import cache
from django.views.decorators.csrf import csrf_exempt


def check_sms_code(request):
    if request.method == 'POST':
        params = json.loads(request.body)
        mobile = params.get('mobile')
        code = params.get('code')

        if not code:
            return my_tool.json_response(outcome=1, message="请先获取短信验证码")

        cache_code = cache.get(mobile)
        if not cache_code:
            return my_tool.json_response(outcome=1, message="验证码已过期，请重新获取")

        if code != cache_code:
            return my_tool.json_response(outcome=1, message="验证码错误")

        return my_tool.json_response(data={})


@csrf_exempt
def register(request):
    if request.method == 'POST':
        params = json.loads(request.body)
        avatar = params.get('avatar')
        name = params.get('username')
        mobile = params.get('mobile')
        code = params.get('code')
        password = params.get('password')


        if not code:
            return my_tool.json_response(outcome=1, message="请先获取短信验证码")

        cache_code = cache.get(mobile)
        if not cache_code:
            return my_tool.json_response(outcome=1, message="验证码已过期，请重新获取")

        if code != cache_code:
            return my_tool.json_response(outcome=1, message="验证码错误")

        if not password:
            return my_tool.json_response(outcome=1, message="密码不能为空")
        try:
            if avatar:
                user = UserInfo(mobile=mobile, password=my_tool.pwd_string(password), username=name, avatar=avatar)
            else:
                user = UserInfo(mobile=mobile, password=my_tool.pwd_string(password), username=name)
        except Exception as e:
            return my_tool.json_response(outcome=1, message=str(e))

        user.save()

        data_dict = user.to_dict()
        data_dict["token"] = my_tool.get_jwt_token(user)
        return my_tool.json_response(data=data_dict)


    return render(request, 'user/register.html')



@csrf_exempt
def login(request):
    if request.method == 'POST':
        params = json.loads(request.body)
        mobile = params.get('mobile')
        code = params.get('code')
        password = params.get('password')
        type = params.get('type')

        if type == 'code':
            if not code:
                return my_tool.json_response(outcome=1, message="请先获取短信验证码")

            cache_code = cache.get(mobile)
            if not cache_code:
                return my_tool.json_response(outcome=1, message="没有验证码或验证码已过期")
            if code != cache_code:
                return my_tool.json_response(outcome=1, message="验证码错误")
            user = UserInfo.objects.get(mobile=mobile)

        else:
            if not password:
                return my_tool.json_response(outcome=1, message="请先输入登录密码")

            user = UserInfo.objects.filter(mobile=mobile, password__exact=my_tool.pwd_string(password)).first()
            if not user:
                return my_tool.json_response(outcome=1, message="用户名或密码错误")

        user.last_login = datetime.datetime.today()
        user.save()

        data_dict = user.to_dict()
        data_dict["token"] = my_tool.get_jwt_token(user)
        return my_tool.json_response(data=data_dict)

    return render(request, 'user/login.html')



def logout(request):
    if request.method == 'POST':
        return my_tool.json_response(message="退出成功")



@csrf_exempt
def send_sms_regist(request):
    if request.method == 'POST':
        mobile = json.loads(request.body).get('mobile')

        if len(mobile) != 11:
            return my_tool.json_response(outcome=1, message="手机号不正确")

        users = UserInfo.objects.filter(mobile=mobile)
        if users.count() != 0:
            return my_tool.json_response(outcome=1, message="手机号已被注册")
        else:
            code = my_tool.get_verification()
            # sms = SendSMS()
            # dict = sms.send_sms(code, mobile)
            result = SendTemplateSMS.sendTemplateSMS(mobile, [code, '10'], 1)
            if result == True:
                cache.set(mobile, code, 60 * 10)
                return my_tool.json_response()
            else:
                return my_tool.json_response(outcome=1,message="验证码发送失败，请稍后再试")


def send_sms_login(request):
    if request.method == 'POST':
        mobile = json.loads(request.body).get('mobile')

        users = UserInfo.objects.filter(mobile=mobile)
        if users.count() == 0:
            return my_tool.json_response(outcome=1, message="账号未注册，请先注册")
        else:
            code = my_tool.get_verification()
            # sms = SendSMS()
            # dict = sms.send_sms(code, mobile)
            result = SendTemplateSMS.sendTemplateSMS(mobile, [code, '10'], 1)
            if result == True:
                cache.set(mobile, code, 60 * 10)
                return my_tool.json_response()
            else:
                return my_tool.json_response(outcome=1,message="验证码发送失败，请稍后再试")


def send_sms(request):
    if request.method == 'POST':
        mobile = request.mobile
        code = my_tool.get_verification()
        # sms = SendSMS()
        # dict = sms.send_sms(code, mobile)
        result = SendTemplateSMS.sendTemplateSMS(mobile, [code, '10'], 1)
        if result == True:
            cache.set(mobile, code, 60 * 10)
            return my_tool.json_response()
        else:
            return my_tool.json_response(outcome=1,message="验证码发送失败，请稍后再试")

import datetime
def userinfo(request):
    if request.method == 'POST':
        user_id = request.user_id
        user = UserInfo.objects.filter(nid=user_id).first()

        user.last_login = datetime.datetime.today()
        user.save()

        data_dict = user.to_dict()
        return my_tool.json_response(data=data_dict)

def modify_userinfo(request):
    if request.method == 'POST':
        user_id = request.user_id

        params = json.loads(request.body)
        mobile = params.get('mobile')
        password = params.get('password')
        avatar = params.get('avatar')
        username = params.get('username')

        user = UserInfo.objects.filter(nid=user_id).first()
        if mobile != None:
            user.mobile = mobile
        if password != None:
            user.password = my_tool.pwd_string(password)
        if avatar != None:
            user.avatar = avatar
        if username != None:
            user.username = username
        user.save()

        data_dict = user.to_dict()
        return my_tool.json_response(data=data_dict)




import os
import time
def upload_file(request):
    if request.method == 'POST':
        file = request.FILES.get('file')
        mobile = file.name.split(".")[0];
        file_name = mobile + '_' + str(int(time.time() * 10))+"."+ file.name.split(".")[1]
        filePath = os.path.join("media/avatars", file_name)
        with open(filePath, 'wb+') as destination:
            for chunk in file.chunks():
                destination.write(chunk)
        return my_tool.json_response(data={"url":'/'+filePath})

Django/makeplan/user/templates/user/register2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>

    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
</head>
<body>

<div class="container" style="padding-top: 70px">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form novalidate autocomplete="off" action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}

                {#第一种#}
{#                    {{ form_obj.as_p }}#}


                {#第二种#}
                {#    {% for obj in form_obj %}#}
                {#        {{ obj.label }}#}
                {#        {{ obj }}#}
                {#    {% endfor %}#}


                {#第三种#}
                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}" class="col-md-3 control-label">{{ form_obj.username.label }}</label>
                    <div class="col-md-9">
                        {{ form_obj.username }}
                        <span class="help-block">{{ form_obj.username.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}" class="col-md-3 control-label">{{ form_obj.password.label }}</label>
                    <div class="col-md-9">
                        {{ form_obj.password }}
                        <span class="help-block">{{ form_obj.password.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.re_password.id_for_label }}" class="col-md-3 control-label">{{ form_obj.re_password.label }}</label>
                    <div class="col-md-9">
                        {{ form_obj.re_password }}
                        <span class="help-block">{{ form_obj.re_password.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.email.id_for_label }}" class="col-md-3 control-label">{{ form_obj.email.label }}</label>
                    <div class="col-md-9">
                        {{ form_obj.email }}
                        <span class="help-block">{{ form_obj.email.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="avatar" class="col-md-3 control-label">头像</label>
                    <div class="col-md-9">
                        <label for="id_avatar"><img id="avatar-img" width="100px" height="100px" src="/static/images/default.png" alt="上传头像"></label>
                        <input accept="image/*" type="file" id="id_avatar" style="display: none">

                        <span class="help-block"></span>
                    </div>
                </div>

{#                button的type决定了form提交还是ajax提交， submit是form提交, button是ajax提交了#}
                <div class="form-group">
                    <button type="button" class="btn btn-primary col-md-12" id="reg-submit">
                        注册
                    </button>
                </div>
            </form>

        </div>
    </div>

</div>


<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>

<script>
    $("#id_avatar").change(function () {
        //alert("123")
        //读取文件的对象
        var fileReader = new FileReader();
        console.log(this.files[0])
        fileReader.readAsDataURL(this.files[0]);    //读取文件是需要时间的
        //读完文件
        fileReader.onload = function () {
            $("#avatar-img").attr("src",fileReader.result)
        }
    })

    //ajax提交
    $("#reg-submit").click(function () {
        var username = $("#id_username").val();
        var password = $("#id_password").val();
        var re_password = $("#id_re_password").val();
        var email = $("#id_email").val();

        //带文件必须是formData
        var formData = new FormData();

        formData.append("username", username);
        formData.append("password", password);
        formData.append("re_password", re_password);
        formData.append("email", email);
        formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());
        formData.append("avatar",$("#id_avatar")[0].files[0])

        $.ajax({
            url:"/user/register/",
            type:"post",
            processData: false,     //传文件需要，告诉jq不要处理传的数据
            contentType: false,     //传文件需要，告诉jq不要设置contentType
            data : formData,        //传文件传formData
            {#data:{#}
            {#    username:username,#}
            {#    password:password,#}
            {#    re_password:re_password,#}
            {#    email:email,#}
            {#    csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),#}
            {#    avatar:$("#id_avatar")[0].files[0]#}
            //},
            success:function (data) {
                if (data.status){
                    console.log(data)

                    $.each(data.msg, function (k,v) {
                        console.log(k,v)
                        console.log($("#id_"+k))
                        //设置text和class
                        $("#id_"+k).next("span").text(v[0]).parent().parent().addClass("has-error");
                    })
                }
                else {
                    console.log(data)
                    location.href = data.msg;
                }
            }
        })
    })

    //将所有的input框绑定获取焦点事件，将所有错误清空
    $("form input").focus(function () {
        $(this).next().text("").parent().parent().removeClass("has-error");
    })

    //blur失去焦点调用
    //input输入时候就请求
    $("#id_username").on("input",function () {
        var username = $(this).val();
        $.ajax({
            url:"/user/check_username/",
            type:"get",
            data:{
                username: username,
            },
            success:function (data) {
                if (data.status){
                    $("#id_username").next("span").text(data.msg).parent().parent().addClass("has-error");
                }
                else {

                }
            }
        })
    })
</script>

</body>
</html>